meta_product_name: "Magsoft"
meta_title: "Magsoft - Adrien Maglo - Personal Website"
meta_description: "Discover my projects & publications"
meta_image: "mag-background.jpg" # should exist in `app/assets/images/`
